services:
    source_postgres:
        image: postgres:latest
        ports:
            - "5433:5432"
        networks:
            - elt_network
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: source_db
        volumes:
            - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

    destination_postgres:
        image: postgres:latest
        ports:
            - "5434:5432"
        networks:
            - elt_network
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: destination_db

    elt_script:
        build:
            context: ./elt
            dockerfile: Dockerfile
        command: ["python", "elt_script.py"]
        networks:
            - elt_network
        depends_on:
            - source_postgres
            - destination_postgres

    dbt:
        image: ghcr.io/dbt-labs/dbt-postgres:1.9.0
        command: 
            [
                "run",
                "--profiles-dir",
                "/root",
                "--project-dir",
                "/dbt"
            ]
        networks:
            - elt_network
        volumes:
            - ./custom_postgres:/dbt
            - ~/.dbt:/root
        depends_on:
            - elt_script
        environment:
            DBT_PROFILE: custom_postgres
            DBT_TARGET: dev

networks:
    elt_network:
        driver: bridge